language: java

sudo: false

jdk:
  - oraclejdk8

env:
  - TEST_DIR=transpiler JSWEET_VERBOSE=false

script:
  - cd $TEST_DIR && mvn clean verify

cache:
  directories:
    - $HOME/.m2

install:
  - nvm install 7.5.0 && nvm use 7.5.0

notifications:
  email:
    recipients:
      - renaud.pawlak@gmail.com
      - louis.grignon@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
